version: "3.9"  # optional since v1.27.0
services:
  backend:
    build: 
      context: . 
      dockerfile: ./backend/Dockerfile
    image: lob-backend:flask
    ports:
      - "5000:5000"
    devices:
      - /dev/usblp0:/dev/usblp0
    restart: always
  frontend:
    build: 
      context: . 
      dockerfile: ./frontend/Dockerfile
    image: lob-frontend:nextjs
    ports:
      - "3000:3000"
    restart: always